- hosts: '*'
  tasks:
  - name: add unifi apt source
    copy:
      content: "deb http://www.ubnt.com/downloads/unifi/debian stable ubiquiti\n"
      dest: /etc/apt/sources.list.d/100-ubnt-unifi.list
  - name: add unifi apt key
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: 06E85760C0A52C50
  - name: install java
    apt:
      name: openjdk-8-jre-headless
      update_cache: true
  # see https://community.ubnt.com/t5/UniFi-Wireless/Ubuntu-14-04-x64-Unifi-4-6-6-very-slow-start-up/m-p/1355803/highlight/true#M121840
  - name: install haveged
    apt:
      name: haveged
      update_cache: true
  - name: install or upgrade unifi
    apt:
      name: unifi
      update_cache: true
      state: latest
  - name: install htop
    apt:
      name: htop
      update_cache: true
